# Make sure to check the documentation at http://goreleaser.com
# ---------------------------
# General
# ---------------------------
before:
  hooks:
    - make all
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^.github:'
      - '^.vscode:'
      - '^test:'

# ---------------------------
# Builder
#
# CGO is enabled and inspiration came from:
#    https://github.com/goreleaser/goreleaser-cross-example
#    https://github.com/goreleaser/goreleaser-cross-example-sysroot
# ---------------------------
builds:
  - id: darwin-amd64
    main: ./cmd/
    binary: alert_system
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/amd64
      - PKG_CONFIG_PATH=/sysroot/macos/amd64/usr/local/lib/pkgconfig
      #- CC=o64-clang
      #- CXX=o64-clang++
      - CC=clang  # Changed from o64-clang
      - CXX=clang++  # Changed from o64-clang++
    #mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}
      #- -s -w -X github.com/bitcoin-sv/{{ .ProjectName }}/cmd.Version={{ .Version }}
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc

  - id: linux-armhf
    main: ./cmd/
    binary: alert_system
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7
    env:
      - CGO_ENABLED=1
      - CC=arm-linux-gnueabihf-gcc  # Make sure this points to the correct executable
      - CXX=arm-linux-gnueabihf-g++
      - CGO_CFLAGS=--sysroot=/sysroot/linux/armhf
      - CGO_LDFLAGS=--sysroot=/sysroot/linux/armhf
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/armhf
      - PKG_CONFIG_PATH=/sysroot/linux/armhf/opt/vc/lib/pkgconfig:/sysroot/linux/armhf/usr/lib/arm-linux-gnueabihf/pkgconfig:/sysroot/linux/armhf/usr/lib/pkgconfig:/sysroot/linux/armhf/usr/local/lib/pkgconfig
    #mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}
      #- -s -w -X github.com/bitcoin-sv/{{ .ProjectName }}/cmd.Version={{ .Version }}
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
# ---------------------------
# Archives + Checksums
# ---------------------------
archives:
  - id: alert_system
    builds:
      - darwin-amd64
      - linux-armhf
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    wrap_in_directory: true

#archives:
#  - wrap_in_directory: true
#    format: tar.gz
#    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}_{{ .Version }}'

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

# ---------------------------
# GitHub Release
# ---------------------------
release:
  prerelease: true
  name_template: "Release v{{.Version}}"

# ---------------------------
# Announce
# ---------------------------
announce:

  # See more at: https://goreleaser.com/customization/announce/#slack
  slack:
    enabled: false
    message_template: '{{ .ProjectName }} {{ .Tag }} is out! Changelog: https://github.com/bitcoin-sv/{{ .ProjectName }}/releases/tag/{{ .Tag }}'
    channel: '#test_slack'
    # username: ''
    # icon_emoji: ''
    # icon_url: ''

  # See more at: https://goreleaser.com/customization/announce/#twitter
  twitter:
    enabled: false
    message_template: '{{ .ProjectName }} {{ .Tag }} is out!'

  # See more at: https://goreleaser.com/customization/announce/#discord
  discord:
    enabled: false
    message_template: '{{ .ProjectName }} {{ .Tag }} is out!'
    # Defaults to `GoReleaser`
    author: ''
    # Defaults to `3888754` - the grey-ish from goreleaser
    color: ''
    # Defaults to `https://goreleaser.com/static/avatar.png`
    icon_url: ''

  # See more at: https://goreleaser.com/customization/announce/#reddit
  reddit:
    enabled: false
    # Application ID for Reddit Application
    application_id: ""
    # Username for your Reddit account
    username: ""
    # Defaults to `{{ .GitURL }}/releases/tag/{{ .Tag }}`
    # url_template: 'https://github.com/bitcoin-sv/{{ .ProjectName }}/releases/tag/{{ .Tag }}'
    # Defaults to `{{ .ProjectName }} {{ .Tag }} is out!`
    title_template: '{{ .ProjectName }} {{ .Tag }} is out!'