version: '3.8'

services:
  alert-system:
    image: docker.io/bsvb/alert-key:latest
    user: root
    environment:
      - ALERT_SYSTEM_CONFIG_FILEPATH=/config.json
    expose:
      - "9908"
    volumes:
      - /home/galt/alert-key/config.json:/config.json:Z
