apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: alert-system
  name: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M
  volumeMode: Filesystem
