apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: alert-system
  name: alert-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alert-system
  strategy: {}
  template:
    metadata:
      labels:
        app: alert-system
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - image: docker.io/bsvb/alert-system:latest
          env:
          - name: ALERT_SYSTEM_DISABLE_RPC_VERIFICATION
            value: "true"
          - name: ALERT_SYSTEM_ENVIRONMENT
            value: "testnet"
          imagePullPolicy: Always
          name: alert-system
          ports:
            - containerPort: 9906
          resources: {}
      restartPolicy: Always
