apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: alert-system
  name: alert-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-system
  strategy: {}
  template:
    metadata:
      labels:
        app: alert-system
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - image: docker.io/galtbv/alert-system:stn
          imagePullPolicy: Always
          name: alert-system
          ports:
            - containerPort: 9906
          resources: {}
      restartPolicy: Always
