# From: https://goreleaser.com/ci/actions/#usage
name: release

env:
  GO111MODULE: on

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Install Dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y libsqlite3-dev # Replace with the actual dependencies your project needs
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5.0.0
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #- name: Syndicate to GoDocs
      #  run: make godocs
