# This workflow executes several linters on changed files based on languages used in your code base whenever
# you push a code or open a pull request.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/github/super-linter
name: super-linter

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v7
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CHECKOV: false # False positive
          VALIDATE_EDITORCONFIG: false  # Not needed in this project
          VALIDATE_GITLEAKS: false # False positives for public keys
          VALIDATE_GO: false # Already running in Go tests
          VALIDATE_GO_MODULES: false # Already running in Go tests
          VALIDATE_JSCPD: false
          VALIDATE_MARKDOWN: false
          VALIDATE_YAML_PRETTIER: false
          VALIDATE_JSON_PRETTIER: false
